matrix:
  include:
    - os: "windows"
      language: go
      env: GO111MODULE=on
      install:
        - choco install make
        - go mod download
      script:
        #- make test
        - make client
        - make controller

    - os: "osx"
      language: go
      env: GO111MODULE=on
      install: go mod download
      script:
        #- make test
        - make client
        - make controller

    - os: "linux"
      language: go
      env: GO111MODULE=on
      install:
        - go mod download
      script:
        #- make test
        - make client
        - make controller
      addons:
        apt:
          packages:
            - libxrandr-dev
            - libx11-dev

    - os: "linux"
      language: node_js
      node_js: node
      install: npm i
      script:
        # - npm run test
        # - npm run build
